export const SEND_MESSAGE_SAGA = "SEND_MESSAGE_SAGA";

//QUIZ
export const GET_SUGGEST_TOPICS = "GET_SUGGEST_TOPICS";
export const GET_QUIZ_TYPES = "GET_QUIZ_TYPES";
export const GENERATE_QUIZ = "GENERATE_QUIZ";
